// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu0cjJJKcd1cKn5ULCGox_EdUzVzxSUZA',
    appId: '1:407206675744:web:89a6111dd11f5e25c80345',
    messagingSenderId: '407206675744',
    projectId: 'ml-project-d2404',
    authDomain: 'ml-project-d2404.firebaseapp.com',
    storageBucket: 'ml-project-d2404.appspot.com',
    measurementId: 'G-8549G44YNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBltdTPzN3MsYBhB_PwSrdbgEgZ7gSAZ4I',
    appId: '1:407206675744:android:35c0f5b0304e9e18c80345',
    messagingSenderId: '407206675744',
    projectId: 'ml-project-d2404',
    storageBucket: 'ml-project-d2404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYlv5uURTxT70PjWkNfX791JrCEmo3B5I',
    appId: '1:407206675744:ios:5ed9a73ff9c442f3c80345',
    messagingSenderId: '407206675744',
    projectId: 'ml-project-d2404',
    storageBucket: 'ml-project-d2404.appspot.com',
    iosClientId: '407206675744-v61o9defcqrif666f72trtq0vr5f8f2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mlproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYlv5uURTxT70PjWkNfX791JrCEmo3B5I',
    appId: '1:407206675744:ios:5ed9a73ff9c442f3c80345',
    messagingSenderId: '407206675744',
    projectId: 'ml-project-d2404',
    storageBucket: 'ml-project-d2404.appspot.com',
    iosClientId: '407206675744-v61o9defcqrif666f72trtq0vr5f8f2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mlproject',
  );
}
